spring:
  application:
     name: config-server
  cloud:
    config:
      server:
        git:
          default-label: master
          uri: https://github.com/Tonyhui/springBoot/
          password: 123abc456?
          username: tonyhui
          searchPaths: respo
      profile:  dev

server:
  port: 8888


